apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # Port within the Kubernetes cluster
      targetPort: 80   # The port on the pod to forward traffic to
      nodePort: 30088   # The port on each node to expose externally
  type: NodePort         # Expose via NodePort
