apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask-app  # Use the locally built image
        imagePullPolicy: IfNotPresent  # Ensure Kubernetes uses the local image if available
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: flask-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
